/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.telaPrin.model;

/**
 *
 * @author Pedro
 */
public class telaCartaoView extends javax.swing.JFrame {

    /**
     * Creates new form telaPrinView
     */
    public telaCartaoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonMAIS = new javax.swing.JButton();
        jButtonORCAMENTOS = new javax.swing.JButton();
        jButtonHOME = new javax.swing.JButton();
        jButtonTRANSACOES = new javax.swing.JButton();
        jButtonRELATORIO = new javax.swing.JButton();
        jButtonENGRENAGEM = new javax.swing.JButton();
        jButtonLUPA = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonMAIS.setContentAreaFilled(false);
        jButtonMAIS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMAIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMAISActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMAIS, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 800, 30, 30));

        jButtonORCAMENTOS.setContentAreaFilled(false);
        jButtonORCAMENTOS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonORCAMENTOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonORCAMENTOSActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonORCAMENTOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 790, 70, 40));

        jButtonHOME.setContentAreaFilled(false);
        jButtonHOME.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonHOME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHOMEActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 790, 30, 30));

        jButtonTRANSACOES.setContentAreaFilled(false);
        jButtonTRANSACOES.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonTRANSACOES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTRANSACOESActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTRANSACOES, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 790, 80, 40));

        jButtonRELATORIO.setContentAreaFilled(false);
        jButtonRELATORIO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRELATORIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRELATORIOActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRELATORIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 790, 60, 40));

        jButtonENGRENAGEM.setContentAreaFilled(false);
        jButtonENGRENAGEM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonENGRENAGEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonENGRENAGEMActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonENGRENAGEM, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 30, 40));

        jButtonLUPA.setContentAreaFilled(false);
        jButtonLUPA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLUPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLUPAActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLUPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 30, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/CARTAO.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, 867));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLUPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLUPAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLUPAActionPerformed

    private void jButtonENGRENAGEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonENGRENAGEMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonENGRENAGEMActionPerformed

    private void jButtonORCAMENTOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonORCAMENTOSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonORCAMENTOSActionPerformed

    private void jButtonTRANSACOESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTRANSACOESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTRANSACOESActionPerformed

    private void jButtonHOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHOMEActionPerformed
        telaPrinView telaPrincipal = new telaPrinView();
        telaPrincipal.setVisible(true);
    }//GEN-LAST:event_jButtonHOMEActionPerformed

    private void jButtonRELATORIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRELATORIOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRELATORIOActionPerformed

    private void jButtonMAISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMAISActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMAISActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaCartaoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaCartaoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaCartaoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaCartaoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaCartaoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonENGRENAGEM;
    private javax.swing.JButton jButtonHOME;
    private javax.swing.JButton jButtonLUPA;
    private javax.swing.JButton jButtonMAIS;
    private javax.swing.JButton jButtonORCAMENTOS;
    private javax.swing.JButton jButtonRELATORIO;
    private javax.swing.JButton jButtonTRANSACOES;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
