/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.telas.view;

import br.com.login.controller.LoginController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Lidia
 */
public class cadastroview extends javax.swing.JFrame {

    /**
     * Creates new form cadastroview
     */
    public cadastroview() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JButtonVoltar = new javax.swing.JButton();
        jButtonCadastrar = new javax.swing.JButton();
        JTextFieldNome = new javax.swing.JTextField();
        JTextFieldEmail = new javax.swing.JTextField();
        JPasswordFieldSenha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JButtonVoltar.setContentAreaFilled(false);
        JButtonVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(JButtonVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 32, 28));

        jButtonCadastrar.setContentAreaFilled(false);
        jButtonCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 327, 120, 40));

        JTextFieldNome.setBackground(new java.awt.Color(254, 168, 0));
        getContentPane().add(JTextFieldNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 310, 40));

        JTextFieldEmail.setBackground(new java.awt.Color(254, 168, 0));
        JTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextFieldEmailActionPerformed(evt);
            }
        });
        getContentPane().add(JTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 198, 310, 40));

        JPasswordFieldSenha.setBackground(new java.awt.Color(254, 168, 0));
        getContentPane().add(JPasswordFieldSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 310, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ref/Cadastro.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextFieldEmailActionPerformed

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        LoginController cadastro = new LoginController();
        try {
            cadastro.cadastroUsuario(this);
        } catch (SQLException ex) {
            Logger.getLogger(cadastroview.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void JButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonVoltarActionPerformed
dispose();

loginview Login = new loginview();
Login.setVisible(true);

    }//GEN-LAST:event_JButtonVoltarActionPerformed

    public JPasswordField getJPasswordFieldSenha() {
        return JPasswordFieldSenha;
    }

    public void setJPasswordFieldSenha(JPasswordField JPasswordFieldSenha) {
        this.JPasswordFieldSenha = JPasswordFieldSenha;
    }

    public JTextField getJTextFieldEmail() {
        return JTextFieldEmail;
    }

    public void setJTextFieldEmail(JTextField JTextFieldEmail) {
        this.JTextFieldEmail = JTextFieldEmail;
    }

    public JTextField getJTextFieldNome() {
        return JTextFieldNome;
    }

    public void setJTextFieldNome(JTextField JTextFieldNome) {
        this.JTextFieldNome = JTextFieldNome;
    }

    
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastroview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastroview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastroview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastroview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastroview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonVoltar;
    private javax.swing.JPasswordField JPasswordFieldSenha;
    private javax.swing.JTextField JTextFieldEmail;
    private javax.swing.JTextField JTextFieldNome;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
